export const cacheKey = {
  profile: 'profile',
  asset: 'asset',
  assetPrice: 'assetPrices',
  dynamicFees: 'dynamicFees',
  assetRates: 'assetsRates',
  userDetails: 'userDetails',
  transactionChart: 'transactionChart',
  dashboardChart: 'dashboardChart',
  orderHistory: 'orderHistory',
  mfaSecret: 'mfaSecret',
  affiliateCommission: 'affiliateCommission',
  affiliateStats: 'affiliateStats',
  checkPaymentService: 'checkPaymentService',
}
